- hosts: localhost
  connection: local
 
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "69875/myweb:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"

